app/config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
]

app/dashboard/urls.py
from django.urls import path

from dashboard import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),

    path('logs/', views.show_logs, name='show-logs'),

    path('myuser/create/',
         views.MyInstagramUserCreate.as_view(),
         name='my-instagram-user-create'),
    path('myuser/delete/',
         views.MyInstagramUserDelete.as_view(),
         name='my-instagram-user-delete'),
    
    path('instagramuser/create/',
         views.InstagramUserCreate.as_view(),
         name='instagram-user-create'),
    path('instagramuser/<int:pk>/delete/',
         views.InstagramUserDelete.as_view(),
         name='instagram-user-delete'),
    
    path('comment/create/',
         views.CommentCreate.as_view(),
         name='comment-create'),
    path('comment/<int:pk>/delete/',
         views.CommentDelete.as_view(),
         name='comment-delete'),
]

app_name = 'dashboard'

app/core/models.py
from django.db import models


class MyInstagramUser(models.Model):
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)

    def __str__(self):
        return self.username


class InstagramUser(models.Model):
    username = models.CharField(max_length=255)

    def __str__(self):
        return self.username


class Post(models.Model):
    user = models.ForeignKey('InstagramUser', on_delete=models.CASCADE)
    post_id = models.CharField(max_length=255)

    def __str__(self):
        return self.post_id


class Comment(models.Model):
    text = models.TextField()

    def __str__(self):
        return self.text

app/core/views.py
from django.shortcuts import render

# Create your views here.

app/dashboard/views.py
import os
import threading
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, DeleteView
from django.contrib import messages

from core import models as core_models


def dashboard(request):
    my_user = core_models.MyInstagramUser.objects.first()
    other_users = core_models.InstagramUser.objects.all()
    comments = core_models.Comment.objects.all()

    context = {
        'my_user': my_user,
        'other_users': other_users,
        'comments': comments,
    }
    return render(request, 'dashboard/dashboard.html', context)


def show_logs(request):
    if not os.path.exists('./report.log'):
        file_content = ''
    else:
        with open('./report.log', 'r') as f:
            file_content = f.read()
    return render(request, 'dashboard/logs.html', {'logs': file_content})


class MyInstagramUserCreate(CreateView):
    model = core_models.MyInstagramUser
    fields = ['username', 'password']
    template_name = 'dashboard/object_create.html'
    success_url = '/dashboard/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_title'] = 'My Instagram User:'
        return context


class MyInstagramUserDelete(DeleteView):
    model = core_models.MyInstagramUser
    template_name = 'dashboard/delete_confirmation.html'
    success_url = '/dashboard/'

    def get_object(self):
        return core_models.MyInstagramUser.objects.first()


class InstagramUserCreate(CreateView):
    model = core_models.InstagramUser
    fields = ['username']
    template_name = 'dashboard/object_create.html'
    success_url = '/dashboard/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_title'] = 'Instagram User:'
        return context


class InstagramUserDelete(DeleteView):
    model = core_models.InstagramUser
    template_name = 'dashboard/delete_confirmation.html'
    success_url = '/dashboard/'


class CommentCreate(CreateView):
    model = core_models.Comment
    fields = ['text']
    template_name = 'dashboard/object_create.html'
    success_url = '/dashboard/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_title'] = 'Comment:'
        return context


class CommentDelete(DeleteView):
    model = core_models.Comment
    template_name = 'dashboard/delete_confirmation.html'
    success_url = '/dashboard/'

app/dashboard/templates/dashboard/dashboard.html
{% extends 'base.html' %}

{% block content %}

{% if messages %}
    {% for message in messages %}
      <div class="alert alert-dark mt-3" role="alert">
        {{ message }}
      </div>
    {% endfor %}
{% endif %}

<div class="row mt-3">
    <div class="col-12">
        <p class="mt-3">
            {% if my_user %}
                <strong>Your User:</strong>{{ my_user.username }} <a class="text-danger" href="{% url 'dashboard:my-instagram-user-delete' %}">[remove]</a>
            {% else %}
                <a class="btn btn-primary mt-3" href="{% url 'dashboard:my-instagram-user-create' %}">Add Your Instagram User</a>
            {% endif %}
        </p>
    </div>
</div>

<div class="row mt-5">
    <div class="col-6">
        <h3>Instagram Users:<a class="btn btn-success float-right" href="{% url 'dashboard:instagram-user-create' %}">Add</a></h3>
        {% if other_users %}
        <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col">Username</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            {% for user in other_users %}
            <tr>
                <td>{{ user.username|truncatechars:50 }}</td>
                <td><a class="text-danger" href="{% url 'dashboard:instagram-user-delete' user.id %}">[remove]</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        {% else %}
            <small>You have to add instagram users which you want to send comment!</small>
        {% endif %}
    </div>

    <div class="col-6">
        <h3>Comments:<a class="btn btn-success float-right" href="{% url 'dashboard:comment-create' %}">Add</a></h3>
        {% if comments %}
        <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col">Text</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            {% for comment in comments %}
            <tr>
                <td>{{ comment.text|truncatechars:50 }}</td>
                <td><a class="text-danger" href="{% url 'dashboard:comment-delete' comment.id %}">[remove]</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        {% else %}
            <small>You have to add comments which you want to send, bot send them randomly!</small>
        {% endif %}
    </div>
</div>
{% endblock %}

app/dashboard/templates/dashboard/delete_confirmation.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
    <div class="col-4 mx-auto">
        <form class="mt-5" method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input class="btn btn-danger" type="submit" value="Confirm">
        </form>
    </div>
</div>
{% endblock %}

app/dashboard/templates/dashboard/logs.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-12">
        <h3 class="mt-3">Logs</h3>
        <textarea class="form-control disabled" style="min-height: 512px;">{{ logs }}</textarea>
    </div>
</div>
{% endblock %}

app/dashboard/templates/dashboard/object_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-12">
        <h3 class="mt-3">{{ object_title }}</h3>
        <form class="mt-5" method="post">{% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-light" type="submit" value="Save">
        </form>
    </div>
</div>
{% endblock %}

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Instagram Comment Bot!</title>
  </head>
  <body>


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/dashboard/">Insta Comment Bot</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'dashboard:show-logs' %}">Log</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    
    
    <div class="container">
    
        {% block content %}
        {% endblock %}

    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>